apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: studentmanagement
    type: "roost-example"
  name: studentmanagement
spec: 
  type: NodePort
  selector: 
    app: studentmanagement
    type: "roost-example"
  ports:
  - name: studentmanagement
    port: 8081
    targetPort: 8081
    nodePort: 30042

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentmanagement
      type: "roost-example"
  template:
    metadata:
      labels:
        app: studentmanagement
        type: "roost-example"
    spec:
      containers:
      - name: studentmanagement
        image: voter:latest
        stdin: true
        tty: true
        env:
        - name: STU
          value: roost-controlplane:30080
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
