apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: librarymanagement
    type: "roost-example"
  name: librarymanagement
spec: 
  type: NodePort
  selector: 
    app: librarymanagement
    type: "roost-example"
  ports:
  - name: librarymanagement
    port: 8082
    targetPort: 8082
    nodePort: 30043

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarymanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarymanagement
      type: "roost-example"
  template:
    metadata:
      labels:
        app: librarymanagement
        type: "roost-example"
    spec:
      containers:
      - name: librarymanagement
        image: librarymanagement:latest
        stdin: true
        tty: true
        env:
        - name: LIB
          value: roost-controlplane:30080
        ports:
        - containerPort: 8082
        imagePullPolicy: Never
