apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: discovery
    type: "roost-example"
  name: discovery
spec: 
  type: NodePort
  selector: 
    app: discovery
    type: "roost-example"
  ports:
  - name: discovery
    port: 8761
    targetPort: 8761
    nodePort: 30041

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
      type: "roost-example"
  template:
    metadata:
      labels:
        app: discovery
        type: "roost-example"
    spec:
      containers:
      - name: discovery
        image: voter:latest
        stdin: true
        tty: true
        env:
        - name: DIS
          value: roost-controlplane:30080
        ports:
        - containerPort: 8761
        imagePullPolicy: Never
